version: '3.8'

services:
  user-service:
    build:
      context: user_service
    ports:
      - "${USER_SERVICE_PORT}:50051"
    depends_on:
      - user-db
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@user-db:${USER_DB_PORT}/${USER_DB}"

  order-service:
    build:
      context: ./order_service
    ports:
      - "${ORDER_SERVICE_PORT}:50052"
    depends_on:
      - order-db
      - user-service
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@order-db:${ORDER_DB_PORT}/${ORDER_DB}"

  user-db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${USER_DB}
    ports:
      - "${USER_DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${ORDER_DB}
    ports:
      - "${ORDER_DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
