# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_service/proto/order.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1forder_service/proto/order.proto\x12\x05order\"H\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\"I\n\x12\x43reateOrderRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\"\x1d\n\x0fGetOrderRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"U\n\x12UpdateOrderRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\",\n\rOrderResponse\x12\x1b\n\x05order\x18\x01 \x01(\x0b\x32\x0c.order.Order2\xc8\x01\n\x0cOrderService\x12>\n\x0b\x43reateOrder\x12\x19.order.CreateOrderRequest\x1a\x14.order.OrderResponse\x12\x38\n\x08GetOrder\x12\x16.order.GetOrderRequest\x1a\x14.order.OrderResponse\x12>\n\x0bUpdateOrder\x12\x19.order.UpdateOrderRequest\x1a\x14.order.OrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_service.proto.order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=42
  _globals['_ORDER']._serialized_end=114
  _globals['_CREATEORDERREQUEST']._serialized_start=116
  _globals['_CREATEORDERREQUEST']._serialized_end=189
  _globals['_GETORDERREQUEST']._serialized_start=191
  _globals['_GETORDERREQUEST']._serialized_end=220
  _globals['_UPDATEORDERREQUEST']._serialized_start=222
  _globals['_UPDATEORDERREQUEST']._serialized_end=307
  _globals['_ORDERRESPONSE']._serialized_start=309
  _globals['_ORDERRESPONSE']._serialized_end=353
  _globals['_ORDERSERVICE']._serialized_start=356
  _globals['_ORDERSERVICE']._serialized_end=556
# @@protoc_insertion_point(module_scope)
